# Sell Order Create Schema
@url = threefoldtoken.order.sell.create
@name = ordersellinput
comment = ""
currency_to_sell = "" (S)   # currency types BTC/ETH/XRP/TFT
currency_accept = (LS)      # can accept more than one currency
price_min =  (N)           # can be defined in any currency
amount = (N)                # amount
expiration =  (D)           # can be defined as e.g. +1h
sell_to = (LS)              # list of wallet addresses which are allowed to buy from me
secret = (LS)               # if used the buyers need to have one of the secrets

# Sell Order Update Schema
@url = threefoldtoken.order.sell.update
comment = ""
@name = ordersellinput
id = (I)                    # Object ID
currency_to_sell = "" (S)   # currency types BTC/ETH/XRP/TFT
currency_accept = (LS)      # can accept more than one currency
amount = (N)                # amount
price_min =  (N)            # can be defined in any currency
expiration =  (D)           # can be defined as e.g. +1h
sell_to = (LS)              # list of wallet addresses which are allowed to buy from me
secret = (LS)               # if used the buyers need to have one of the secrets

# Buy Order Create Schema
@url = threefoldtoken.order.buy.create
@name = orderbuyinput
comment = ""
currency_to_buy = "" (S)    # currency types BTC/ETH/XRP/TFT
currency_mine = (LS)        # which of my currencies I am selling (can be more than 1)
price_max = 0 (N)           # can be defined in any currency
amount = (N)                # amount
expiration =  (D)           # can be defined as e.g. +1h
buy_from = (LS)             # list of wallet addresses which I want to buy from
secret = "" (S)             # the optional secret to use when doing a buy order, only relevant when buy_from used

# Buy Order Update Schema
@url = threefoldtoken.order.buy.update
comment = ""
@name = orderbuyinput
id = (I)                    # Object ID
currency_to_buy = "" (S)    # currency types BTC/ETH/XRP/TFT
currency_mine = (LS)        # which of my currencies I am selling (can be more than 1)
price_max = 0 (N)           # can be defined in any currency
amount = (N)                # amount
expiration =  (D)           # can be defined as e.g. +1h
buy_from = (LS)             # list of wallet addresses which I want to buy from
secret = "" (S)             # the optional secret to use when doing a buy order, only relevant when buy_from used
