@url = test.gedis.cmd
name = ""
comment = ""
schemacode = ""

@url = test.gedis.serverschema
@name = schematest1
cmds = (LO) !test.gedis.cmd

@url = test.gedis.cmd1
@name = cmd12
cmd = (O) !test.gedis.cmd
cmd2 = (O) !test.gedis.cmd

