@url = threefoldtoken.order.sell
name = ""
comment = ""
price_min = 0 (N)  #can be defined in any currency
expiration =  (D)  #can be defined as e.g. +1h
sell_to = (LS)     #list of wallet addresses which are allowed to buy from me
secret = (LS)      #if used the buyers need to have one of the secrets 

@url = threefoldtoken.order.buy
name = ""
comment = ""
price_max = 0 (N)  #can be defined in any currency
expiration =  (D)  #can be defined as e.g. +1h
sell_from = (LS)     #list of wallet addresses which I want to buy from
secret = "" (S)    #the optional secret to use when doing a buy order, only relevant when sell_from used


